name: nginx-custom
version: 0.0.1
summary: small, powerful, scalable web/proxy server
description: Nginx ("engine X") is a high-performance web and reverse proxy server created by Igor Sysoev. It can be used both as a standalone web server and as a proxy to reduce the load on back-end HTTP or mail servers.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18
architectures:
  - amd64

apps:
  nginx:
    command: bin/nginx
    #daemon: forking
    #stop-command: bin/nginx -s stop
    #stop-timeout: 10s
    plugs: [network, network-bind]

parts:
  nginx:
    plugin: dump
    source: https://github.com/seanlano/nginx.git
    source-type: git
    source-tag: release-1.13.6_snap-fix
    override-build: |
      snapcraftctl build
      wget https://sourceforge.net/projects/libpng/files/zlib/1.2.11/zlib-1.2.11.tar.gz/download -O zlib.tar.gz
      mkdir zlib
      tar xvf zlib.tar.gz --strip-components 1 -C zlib/
      wget https://ftp.pcre.org/pub/pcre/pcre-8.41.tar.bz2 -O pcre.tar.bz2
      mkdir pcre
      tar xvf pcre.tar.bz2 --strip-components 1 -C pcre/
      auto/configure --prefix=/snap/docserver/current/etc/nginx --sbin-path=/snap/docserver/current/usr/sbin --conf-path=/snap/docserver/current/etc/nginx/nginx.conf --error-log-path=/var/snap/docserver/current/var/log/nginx/error.log --http-log-path=/var/snap/docserver/current/var/log/nginx/access.log --pid-path=/var/snap/docserver/current/var/run/nginx.pid --lock-path=/var/snap/docserver/current/var/lock/nginx.lock --http-client-body-temp-path=/var/snap/docserver/current/var/cache/nginx/client_temp --http-proxy-temp-path=/var/snap/docserver/current/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/snap/docserver/current/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/snap/docserver/current/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/snap/docserver/current/var/cache/nginx/scgi_temp #--user=nginx --group=nginx --with-http_gzip_static_module --with-http_gunzip_module --with-http_realip_module --with-http_mp4_module --with-http_flv_module --with-http_dav_module --with-http_secure_link_module --with-http_ssl_module --with-http_addition_module --with-http_sub_module --with-http_stub_status_module --with-http_random_index_module --with-http_auth_request_module --with-mail --with-mail_ssl_module --with-file-aio
      make
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp objs/nginx $SNAPCRAFT_PART_INSTALL/bin/nginx
    build-packages:
        - libc6
        - libgd3
        - libgeoip1
        - libssl1.0.0
        - libxml2
        - libxslt1.1
        - build-essential
        - autoconf
        - automake
        - pkg-config
        - libtool